### ISSUE TITLE
Selectively serialize objects as links

### ISSUE THREAD

**Issue by jenniferplusplus** [Letterbook/Letterbook.ActivityPub#24]
At least some of the time, collections on objects should be serialized as links, rather than as whole collections. Other objects may also sometimes be better represented as links than as objects.

**Comment by warriordog** [comment]
@jenniferplusplus Having tackled this before, the easiest way to do it is to explicitly check all of the properties (except href) before serialization. If none are populated, then convert to string instead. But this has some downsides:
* Any new properties have to be added to this check
* It plays very poorly with extensions (#9)

I haven't found a great alternative yet, but I could search for one if you'd like. Otherwise, I'd be happy to implement this using the simply approach described above.

**Comment by jenniferplusplus** [comment]
@warriordog That seems like a place to start, at least. I don't love having to update those checks, though. If I was doing it, I would explore doing it with reflection (`Type.GetProperties()` or similar)

**Comment by warriordog** [comment]
@jenniferplusplus sounds good. I have actually tried this with reflection before, and that *also* gets messy. But I can do it that way if you prefer?

**Comment by jenniferplusplus** [comment]
It was just a thought
